import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { FreeMode } from 'swiper';

import { Swiper, SwiperSlide } from 'swiper/react';

import { useEffect, useState } from 'react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/free-mode';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [slideRef, setSlideRef] = useState<any>();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Swiper
          spaceBetween= {50}
          slidesPerView= {5}
          loop={true}
          modules={[FreeMode]}
          freeMode={true}
          onSwiper={(swiper) => setSlideRef(swiper)}
      >
        <SwiperSlide><div className='card'>Slide 1</div></SwiperSlide>
        <SwiperSlide><div className='card'>Slide 2</div></SwiperSlide>
        <SwiperSlide><div className='card'>Slide 3</div></SwiperSlide>
        <SwiperSlide><div className='card'>Slide 4</div></SwiperSlide>
        <SwiperSlide><div className='card'>Slide 5</div></SwiperSlide>
        <SwiperSlide><div className='card'>Slide 6</div></SwiperSlide>
        <SwiperSlide><div className='card'>Slide 7</div></SwiperSlide>
        <SwiperSlide><div className='card'>Slide 8</div></SwiperSlide>
        <SwiperSlide><div className='card'>Slide 9</div></SwiperSlide>
        <SwiperSlide><div className='card'>Slide 10</div></SwiperSlide>
      </Swiper>

      <div className='buttons'>
        <button onClick={() => slideRef.slidePrev()}>{'<-'}</button>
        <button onClick={() => slideRef.slideNext()}>{'->'}</button>
      </div>
      </main>
    </>
  )
}
